- name: Install certificates
  become: true
  block:
    - name: Copy certificate
      ansible.builtin.copy:
        src: etc/ssl/certs/{{ ssl.cert }}
        dest: /usr/share/ca-certificates/{{ dns.domain }}/
        mode: u=rw

    - name: Update /etc/ca-certificates.conf
      ansible.builtin.lineinfile:
        path: /etc/ca-certificates.conf
        line: "{{ dns.domain }}/{{ ssl.cert | basename }}"
        state: present

    - name: Update CA certificates
      ansible.builtin.command: /usr/sbin/update-ca-certificates --verbose
      changed_when: false
