# override these variables in vars.yml

username: "{{ ansible_env.USER }}"

config:
  user: /opt/config/user
  gpg: /opt/softpack/gpg

spack_src: https://github.com/spack/spack
spack_path: /opt/spack
spack_version: 6aa4c29119

spack:
  cache: /opt/spack-cache
  environments: /opt/softpack/environments
  manifest:
    spack:
      container:
        format: singularity
        images:
          os: ubuntu:20.04
          spack: v0.19.2
      repos:
        - /opt/spack-repo

singularity:
  build:
    bind: /opt/spack-cache,/opt/softpack/gpg

dns:
  domain:
  zone:

ssl:
  cert:

ldap:
  uri:
  base:
  filter:

artifacts:
  repo:
    uri:
    token:

  oras:
    - username:
      token:
