---
- name: Provision all hosts
  hosts: all
  roles:
    - init

- name: Provision build-controller
  hosts: build-controller
  vars_files:
    - defaults.yml
    - vars.yml
  roles:
    - nginx
    - python
    - spack
    - certificates
    - ldap
    - artifacts
    - builder

- name: Provision build-nodes
  hosts: build_nodes
  roles:
    - python

- name: Cleanup all hosts
  hosts: all
  roles:
    - cleanup
