- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ username }}"
    mode: "{{ item.mode }}"
  loop:
    - path: "{{ builder_path }}"
      mode: u=rwx,o=rx,g=rx
    - path: "{{ builder_config | dirname }}"
      mode: u=rwx,g=-,o=-
    - path: "{{ spack.cache }}"
      mode: u=rwx,o=rx,g=rx
    - path: "{{ spack.environments }}"
      mode: u=rwx,o=rx,g=rx

- name: Clone git repo
  ansible.builtin.git:
    repo: "{{ builder_repo }}"
    version: "{{ builder_version }}"
    dest: "{{ builder_path }}"
    accept_hostkey: true

- name: Install python packages
  ansible.builtin.pip:
    name: "{{ item }}"
    virtualenv: "{{ builder_venv }}"
    virtualenv_command: python -m venv
  loop:
    - pip == 23.0.1
    - poetry == 1.4.0

- name: Write config file
  vars:
    config:
      spack: "{{ spack }}"
      artifacts: "{{ artifacts }}"
      singularity: "{{ singularity }}"
  ansible.builtin.copy:
    content: "{{ config | to_nice_yaml(indent=2) }}"
    dest: "{{ builder_config }}"
    mode: u=rw,g=-,o=-

- name: Clone spack templates
  ansible.builtin.git:
    repo: "{{ templates_repo }}"
    version: "{{ templates_version }}"
    dest: "{{ templates_path }}"
    accept_hostkey: true

- name: Install dependencies
  ansible.builtin.command: "{{ builder_venv }}/bin/poetry install -E dev"
  args:
    chdir: "{{ builder_path }}"
    creates: "{{ builder_venv }}/bin/softpack-builder"

- name: Setup prefect server
  become: true
  block:
    - name: Setup systemd services
      ansible.builtin.template:
        src: files/lib/{{ item.path }}
        dest: /lib/{{ item.path }}
        mode: u=rw,g=r,o=r
      with_community.general.flattened:
        - files/lib
      when: item.state == "file"

    - name: Enable systemd service
      ansible.builtin.file:
        src: /lib/{{ item.path }}
        dest: /etc/{{ item.path | dirname }}/multi-user.target.wants/{{ item.path | basename }}
        state: link
      with_community.general.flattened:
        - files/lib
      when: item.state == 'file'

    - name: Setup prefect server site
      ansible.builtin.copy:
        src: files/etc/
        dest: /etc
        mode: u=rw,g=r,o=r
        directory_mode: u=rwx,o=rx,g=rx

    - name: Enable prefect server site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/prefect-server
        dest: /etc/nginx/sites-enabled/prefect-server
        state: link
      notify: Restart nginx

    - name: Remove default site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Restart nginx

- name: Configure prefect service
  vars:
    domain: "{{ [dns.zone | default(''), dns.domain] | select() | join('.') }}"
    hostname: "{{ ansible_hostname }}.{{ domain }}"
  ansible.builtin.shell: |
    source {{ builder_venv }}/bin/activate
    prefect config set PREFECT_API_URL=http://{{ hostname }}/api
  args:
    executable: /bin/bash
    creates: "{{ prefect_profile_path }}"

- name: Copy prefect profile
  become: true
  ansible.builtin.copy:
    src: "{{ prefect_profile_path }}"
    remote_src: true
    dest: "{{ config.user }}/{{ prefect_profile | dirname }}/"
    mode: u=rw,o=r,g=r

- name: Start services
  become: true
  ansible.builtin.systemd:
    name: "{{ item | basename }}"
    daemon_reload: true
    enabled: true
    state: started
  with_fileglob:
    - files/lib/systemd/system/*.service
